name: Publish Packages
on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bukkit
          path: target/*
